### ISSUE TITLE
throw new Error('Parameter token or opts.auth is required');

### ISSUE THREAD

**Issue by geekyouth** [Bounceapp/render-action#129]
```yaml
jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - name: Render deploying
        uses: bounceapp/render-action@0.2.0
        with:
          token: ${{ secrets.RENDER_TOKEN_GITHUB }}
          service-id: srv-ce42vsirrk0djk3sf250
          email: ${{ secrets.RENDER_EMAIL_GITHUB }}
          password: ${{ secrets.RENDER_PASSWORD_GITHUB }}
```

```
/home/runner/work/_actions/bounceapp/render-action/0.2.0/webpack:/render-action/node_modules/@actions/github/lib/internal/utils.js:26
        throw new Error('Parameter token or opts.auth is required');
```

i have provided all needed paramters, but it does not work.
